baseURL = 'http://ramsocdev.danlee.uk'
languageCode = 'en-us'
title = 'Rambling & Hiking'

theme = "greenandgold"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Committee"
    pre = "pen-tool"
    url = "/committee/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4