baseURL = 'http://ramsocdev.danlee.uk/'
languageCode = 'en-us'
title = 'Rambling & Hiking'

theme = "greenandgold"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1


  [outputs]
    home = ["HTML"]
    section = ["HTML", "Calendar"]
    page = ["HTML"]