baseURL = 'https://ramsoc.co.uk'
languageCode = 'en-us'
title = 'Rambling & Hiking'
DefaultContentLanguage = "en"
theme = "greenandgold"
buildFuture = true
googleAnalytics = 'G-9JLNQSX5RH'
assetDir = "static"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Rambling & Hiking"
  github = "https://github.com/UoN-Rambling-Hiking"
  sitename = "Rambling & Hiking"
  description = 'The University of Nottingham Rambling & Hiking Club. We run weekly walks, socials and trips away.'
  title = 'Rambling & Hiking'
  images = ['img/banner.jpg']

[taxonomies]
  series = 'series'

[languages]
  [languages.en]
    languageName =  "English"
    languageCode = "en-us"
    weight = 1

[menu]
  [[menu.main]]
    name = "Get Involved"
    weight = 2
  [[menu.main]]
    name = "About"
    weight = 3
  [[menu.main]]
    name = "Gear"
    weight = 4


  [outputs]
    home = ["HTML"]
    section = ["HTML", "Calendar"]
    page = ["HTML"]


[imaging]
  hint = 'photo'
  quality = 90
  anchor = "center"
  [imaging.exif]
    disableDate = true
    disableLatLong = false
    excludeFields = ''
    includeFields = ''

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
